### ISSUE TITLE
Convert the site to Jekyll or some other static site generator that isn't based on a JavaScript framework

### ISSUE THREAD

**Issue by kyle-hall** [kyle-hall/website#15]
I'm not happy with how things are going with Next. I can't get a custom 404 page for a static site, and I can't do all of the normal CSS things like pseudo-selectors, global styles, or using the cascade. Jekyll is something I've used before that I think will better suited to the kind of site I want to make.

**Comment by kyle-hall** [comment]
After some research, I'm going to checkout Eleventy and default back to Jekyll if that doesn't work out.

**Comment by kylehall-ixo** [comment]
Done.
