### ISSUE TITLE
Code example enhancements

### ISSUE THREAD

**Issue by kylehall-ixo** [kyle-hall/website#45]
I think it would be fun to add little tabs to the code examples displaying the language of the example.

**Comment by kylehall-ixo** [comment]
The left border of the example would look good a little thicker, too. 7px looks good to me.

**Comment by kyle-hall** [comment]
Increase text size. Try 16px instead.

**Comment by kyle-hall** [comment]
Remove the padding-bottom: 20px rule from the code-example class.
